CREATE TABLE IF NOT EXISTS Note (
    id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    title VARCHAR(50),
    content VARCHAR(1000)
);
INSERT INTO Note (title, content) VALUES ('title', 'content');